#!/bin/bash

## sync an apollo environment from it's parent NA beta
# check num args
if [ "$#" -ne 2 ] ; then
   echo "\nInvalid number of arguments.\n"
   echo "Usage:"
   echo "   apollo-parent-sync <env> <stage>"
   exit 1
fi

# parse arg
env=${1}
stage=${2}

echo "Syncing $env/$stage to $env/yehyeh/$stage\n"
output=$(/apollo/env/ApolloCommandLine/bin/apollo sync --source-environment-stage $env/$stage $env/yehyeh/$stage)
deploymentid=$(echo $output | jq '.deployment_id')
echo "https://apollo.amazon.com/deployments/$deploymentid"
