#!/usr/bin/python3

import argparse
import json
import os
import subprocess
import sys

from util.apollo import bcolors
from util.apollo import print_subprocess_error
from util.apollo import wait_for_deployment

parser = argparse.ArgumentParser(description=
        'Sync an Apollo environment from parent.\n'\
                '\n'\
                'This script takes a given Apollo environment name and stage\n'\
                'and syncs it to a child environment with the user\'s alias.\n'\
                '\n'\
                'Example usage:\n'\
                '   apollo-sync-parent ShipmentInjectionRequestManager/NA Beta',
        formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('env', type=str, help='Environment name')
parser.add_argument('stage', type=str, help='Environment stage')

args = parser.parse_args()

user = os.getlogin()
parent_env = args.env + '/' + args.stage
child_env = args.env + '/' +  user + '/' + args.stage

print(bcolors.OKGREEN \
        + "Syncing " \
        + parent_env \
        + " to " \
        + child_env \
        + bcolors.ENDC)

apollo_sync = subprocess.run(
        [
            '/apollo/env/ApolloCommandLine/bin/apollo',
            'sync',
            '--source-environment-stage',
            parent_env,
            child_env
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)

if apollo_sync.stderr:
    print_subprocess_error(apollo_sync)
    sys.exit(1)

result_json = json.loads(apollo_sync.stdout.decode('utf-8'))
deployment_id = str(result_json['deployment_id'])

print(bcolors.OKGREEN \
        + 'Created deployment https://apollo.amazon.com/deployments/' \
        + deployment_id \
        + bcolors.ENDC)

result = wait_for_deployment(deployment_id)

if result == 0:
    print(bcolors.OKGREEN \
            + 'Successfully synced ' \
            + parent_env \
            + ' to ' \
            + child_env \
            + bcolors.ENDC)
else:
    print(bcolors.FAIL \
            + 'Failed to sync ' \
            + parent_env \
            + ' to ' \
            + child_env \
            + bcolors.ENDC)

sys.exit(result)

