#!/bin/bash

## deploy an apollo environment based on the current brazil WS
if [ "$#" -ne 2 ] ; then
   echo "\nInvalid number of arguments.\n"
   echo "Usage:"
   echo "   apollo-deploy-ws <env> <stage>"
   exit 1
fi

# parse arg
env=${1}
stage=${2}

# get the VFI to deploy
vs=$(brazil ws show | awk '/Version Set:/{sub(/.*Version Set:\s*/, ""); print}' | sed -r 's/@/@B/g')
echo "Deploying $vs to $env/yehyeh/$stage\n"
output=$(apollo deploy --version-set-revision $vs $env/yehyeh/$stage)
deploymentid=$(echo $output | jq '.deployment_id')
echo "https://apollo.amazon.com/deployments/$deploymentid"
