#!/bin/bash

## Re-deploy SIRM overrides to dev-desktop
echo "\nDeploying ShipmentInjectionRequestManager:\n"
# if forced or a valid target, run the command
brazil ws env update
sudo /apollo/bin/runCommand -a Deactivate -e ShipmentInjectionRequestManager
sudo /apollo/bin/runCommand -a Activate -e ShipmentInjectionRequestManager
