#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if ! git clone ssh://git.amazon.com/pkg/Yehyeh-scripts ~/Yehyeh-scripts 2>/dev/null && [ -d ~/Yehyeh-scripts ] ; then
   echo "Yehyeh-scripts already exists in home directory."
fi

