#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.5
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config split_ratio                  0.50

yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xffff6700
yabai -m config normal_window_border_color   0xff555555

yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10


# float system prefs
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float BTT prefs
yabai -m rule --add title="^BetterTouchTool$" manage=off

# float any settings windows
yabai -m rule --add title="Settings$" manage=off

# float Cisco AnyConnect
yabai -m rule --add app='^Cisco AnyConnect Secure Mobility Client$' manage=off

# float IntelliJ prefs
#yabai -m rule --add app='IntelliJ IDEA' title='^$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Preferences' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Edit configuration' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Connect to Remote Workspace' manage=off

# float JetBrains toolbox
yabai -m rule --add app='JetBrains Toolbox' manage=off

# float activity monitor
yabai -m rule --add app='^Activity Monitor$' manage=off

# float amazon chime
yabai -m rule --add app='^Amazon Chime$' manage=off

# float outlook meeting reminders
yabai -m rule --add app='^Microsoft Outlook$' title='Reminder' manage=off

# float finder
yabai -m rule --add app='^Finder$' manage=off

# float friendly streaming ops
yabai -m rule --add app='^Friendly Streaming$' title='Untitled' manage=off

# float connections
yabai -m rule --add app='^Amazon Connections$' manage=off

# set up spacebar
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# Limelight addon (Kill it and start it each time Yabai starts)
#killall limelight &>/dev/null
#limelight &>/dev/null &

echo "yabai configuration loaded.."
