#!/bin/bash

# alias for running brazil commands on all packages
if [ $# -lt 1 ]; then
   echo 'No command provided.'
   exit 1
fi
local cmd
local div=`printf -- '-%.0s' {1..60}`
export div
printf -v cmd 'echo "\n$div"; echo "${name}"; echo "$div"; (%s)' "$*"
brc -all --continue $cmd
