version: "1.0"
properties:
  serverversion:
    lastchecktimestamp: -62135596800
    version: 0.0.0.0
  images:
    awsregion: us-west-2
  cli:
    completionscriptpaths:
      zsh: ~/.config/zsh/completion/_rde
  midway:
    cookiehash: 122ee0157ad3faf1b64e75264684a0a6b59f37a5
