#!/bin/bash

source "$HOME/.config/sketchybar/fonts.sh"
source "$HOME/.config/sketchybar/colors.sh"

# Variables
ITEMS="$HOME/.config/sketchybar/items"
PLUGINS="$HOME/.config/sketchybar/plugins"
RIGHT="right"
LEFT="left"

# General bar appearance
bar=(
   height=24
   blur_radius=50
   position=top
   padding_left=0
   padding_right=0
)
sketchybar --bar "${bar[@]}"

# Default values
defaults=(
   updates=when_shown
   drawing=on
   icon.font="$FONT_AWESOME"
   label.font="$HELVETICA"
   icon.color=$WHITE
   label.color=$WHITE
   background.padding_left=0
   background.padding_right=0
   background.height=24
   icon.padding_left=4
   icon.padding_right=4
   icon.y_offset=0
)
sketchybar --default "${defaults[@]}"

# Custom event for float
sketchybar --add event float_change

# Left
source "$ITEMS/transition.sh" $GRAY_DARK $GRAY_DARK $RIGHT
source "$ITEMS/spaces.sh"
source "$ITEMS/transition.sh" $GRAY_DARK $YELLOW $RIGHT
source "$ITEMS/float.sh"
source "$ITEMS/transition.sh" $YELLOW $CLEAR $RIGHT
#source "$ITEMS/network.sh"
source "$ITEMS/vpn.sh"

# Right
source "$ITEMS/time.sh"
source "$ITEMS/transition.sh" $GRAY_DARK $YELLOW $LEFT
source "$ITEMS/date.sh"
source "$ITEMS/transition.sh" $YELLOW $GRAY_LIGHT $LEFT amphetamine_transition
source "$ITEMS/amphetamine.sh"
source "$ITEMS/transition.sh" $GRAY_LIGHT $GRAY_LIGHT $LEFT amphetamine_battery_transition
source "$ITEMS/battery.sh"
source "$ITEMS/transition.sh" $GRAY_LIGHT $GRAY_LIGHT $LEFT battery_transition
source "$ITEMS/weather.sh"
source "$ITEMS/transition.sh" $GRAY_LIGHT $CLEAR $LEFT battery_monitor_transition
source "$ITEMS/media.sh"
#source "$ITEMS/monitors.sh"

# Center
#source "$ITEMS/title.sh"
#source "$ITEMS/stack.sh"

# Finish set up
sketchybar --update

echo "sketchybar configuration loaded.."
