#!/usr/bin/env expect -f

# Kerberos initialization with no user interaction
# This script can be used standalone or with the initall script.
# This script requires your Amazon password to be stored in the
# Mac keychain under amzn_pwd.
#
# security add-generic-password -a <user> -s <service> -w

# InfoSec consultation: https://t.corp.amazon.com/P33840651 (NO AWS AppSec)
# USAGE: $kinit-onetouch

set my_user "$env(USER)"
set my_service amzn_pwd
set my_password [exec security find-generic-password -a $my_user -s $my_service -w]
set timeout -1
spawn kinit
match_max 100000
expect -re "$my_user@ANT\.AMAZON\.COM's password: "
send -- "$my_password\r"
expect eof
