#!/usr/bin/env expect -f

# InfoSec consultation: https://t.corp.amazon.com/P33840651 (NO AWS AppSec)
# https://w.amazon.com/bin/view/Users/hqzhang/VPNOneTouch/
# USAGE: $mwinit-onetouch

set my_user "$env(USER)"
set my_service midway_pin
set my_password [exec security find-generic-password -a $my_user -s $my_service -w]
send_user "Press the button on your YubiKey...\n"
expect_user -timeout 60 -re "(.*)\n"
set my_yubikey $expect_out(1,string)
set timeout -1
spawn mwinit -s -o --aea
match_max 100000
expect -exact "PIN for $my_user: "
send -- "$my_password\r"
expect -re "\r\nPress the button on your .*\.\.\.\r\n"
send -- "$my_yubikey\r"
expect eof
